// AUTO-GENERATED by scripts/extract-college-colors.mjs — do not edit manually
// Re-generated automatically on `npm run dev` and `npm run build`.

export const COLLEGE_COLORS: Record<string, string> = {
  "alameda": "#2069ab",
  "berkeleycc": "#00728b",
  "cabrillo": "#4d83bb",
  "canada": "#005542",
  "ccsf": "#1e3a5f",
  "cmc": "#385e97",
  "contracosta": "#4a74a2",
  "deanza": "#1e3a5f",
  "diablo": "#1e3a5f",
  "evergreen": "#1e894a",
  "foothill": "#b1122b",
  "gavilan": "#1b3d6e",
  "laney": "#2c784c",
  "losmedanos": "#1e3a5f",
  "merritt": "#3d65ac",
  "sanjosecity": "#2f1a45",
  "skyline": "#f13d39",
};
