"""backend_test_docstrings check: every backend test file has a module
docstring with a Coverage: section.

The backend test suite documents each test file in plain language via a
top-of-file module docstring whose shape is defined in
`backend/docs/testing.md`. The docstring names the unit under test,
optionally describes context, and lists coverage areas as bullets under
a `Coverage:` label. This file-level summary is what keeps the suite
legible as it grows — a reader can open any test file and understand
what it guards without reading every `def test_*` function.

This check enforces the convention mechanically so it cannot rot. For
each file matching `backend/<feature>/test_*.py` (excluding the
integration tests tree, which has different conventions and no pass
requirement), the check verifies:

1. The module has a docstring — the first statement in the file body
   is a string literal, accessible via `ast.get_docstring`.
2. The docstring contains the label `Coverage:`.

The check does not enforce the contents of the Coverage bullets — the
convention relies on author discipline at write time for that, and a
stricter parser would create friction without much safety gain. But a
test file missing the docstring entirely, or whose docstring lacks a
Coverage section, is a clear drift signal and blocks the audit.

This check mirrors atlas_test_headers in intent and shape. The two
together keep the backend and atlas test suites at parity in per-file
legibility, regardless of their different runner and language choices.
"""

from __future__ import annotations

import ast
from pathlib import Path
from typing import List

from .base import Check, CheckResult, Status


# Directories under backend/ that may contain test files subject to this
# check. Matches the feature directories plus shared-infrastructure dirs
# that currently host unit tests. Integration tests under tests/integration/
# are deliberately excluded — they follow a different convention and run
# outside the unit suite.
_SCANNED_DIRS = (
    "students",
    "courses",
    "occupations",
    "employers",
    "partnerships",
    "strong_workforce",
    "ontology",
    "llm",
)


class BackendTestDocstringsCheck(Check):
    name = "backend_test_docstrings"
    description = "every backend test file has a module docstring with a Coverage: section"

    def run(self, repo_root: Path) -> CheckResult:
        backend_dir = repo_root / "backend"
        if not backend_dir.exists():
            return CheckResult(
                check=self.name,
                status=Status.SKIP,
                details=f"backend/ not found at {backend_dir}",
            )

        test_files = list(_find_test_files(backend_dir))
        if not test_files:
            return CheckResult(
                check=self.name,
                status=Status.SKIP,
                details="no backend test files found under the scanned directories",
            )

        problems: List[str] = []
        for path in test_files:
            issues = _check_file(path)
            if issues:
                try:
                    rel = path.relative_to(repo_root)
                except ValueError:
                    rel = path
                for issue in issues:
                    problems.append(f"  {rel}: {issue}")

        if problems:
            return CheckResult(
                check=self.name,
                status=Status.FAIL,
                details=(
                    f"Found {len(problems)} test file(s) missing the module "
                    f"docstring or Coverage section:\n" + "\n".join(problems)
                ),
                resolution=(
                    "Every test_*.py file under backend/<feature>/ must begin "
                    "with a module docstring containing a 'Coverage:' label "
                    "and a bullet list of what the file guards. See "
                    "backend/docs/testing.md for the full convention."
                ),
                items_checked=len(test_files),
            )

        return CheckResult(
            check=self.name,
            status=Status.PASS,
            items_checked=len(test_files),
        )


def _find_test_files(backend_dir: Path):
    """Yield every test_*.py file under the scanned feature directories."""
    for subdir in _SCANNED_DIRS:
        scan_root = backend_dir / subdir
        if not scan_root.exists():
            continue
        for path in scan_root.rglob("test_*.py"):
            # Skip anything inside __pycache__ — generated bytecode is out of scope.
            if "__pycache__" in path.parts:
                continue
            yield path


def _check_file(path: Path) -> List[str]:
    """Return a list of issues for a single test file. Empty = passing."""
    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        return [f"could not read file: {e}"]

    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        return [f"syntax error while parsing: {e}"]

    docstring = ast.get_docstring(tree)
    if docstring is None:
        return [
            "module docstring is missing; the file must begin with a "
            "triple-quoted string describing the unit under test and "
            "listing Coverage: bullets"
        ]

    if "Coverage:" not in docstring:
        return [
            "module docstring is present but lacks a 'Coverage:' label; "
            "add a 'Coverage:' line followed by bullet points naming what "
            "the file guards"
        ]

    return []
